### ISSUE TITLE
stripe config not working as expected

### ISSUE THREAD

**Issue by winzig** [stripe/stripe-cli#343]
Using version stripe-cli 1.2.7. A confusing sequence:

```
Toms-Work-Mac:~ tom$ stripe config color auto
config let's you set and unset specific configuration values for your profile if
you need more granular control over the configuration.

Usage:
  stripe config [flags]

Examples:
  stripe config list
  stripe set color off
  stripe unset color

Toms-Work-Mac:~ tom$ stripe set color off
Unknown command "set" for "stripe". Did you mean "get"?
If not, see "stripe --help" for a list of available commands.
```

None of those example commands work. 

I'm trying to either turn colors off, or configure them to be more readable in my environment (dark purple on translucent black background is hard for me to read).

**Comment by winzig** [comment]
Also, is the config file options defined somewhere? E.g. all of the available options that can be configured in the config file?

**Comment by ob-stripe** [comment]
Hi @winzig, sorry about that. We fixed the examples in the latest version, v1.2.8, which will be available shortly.

> Also, is the config file options defined somewhere? E.g. all of the available options that can be configured in the config file?

Note at this time. We'll look into adding a complete reference to the wiki.

**Comment by winzig** [comment]
@ob-stripe 

I downloaded 1.2.8, but still having problems. I see the examples are changed for `stripe config`, but they aren't working for me:

```
Toms-Work-Mac:diag.net tom$ stripe config
config let's you set and unset specific configuration values for your profile if
you need more granular control over the configuration.

Usage:
  stripe config [flags]

Examples:
  stripe config --list
  stripe config --set color off
  stripe config --unset color

Flags:
  -e, --edit                Open an editor to the config file
  -h, --help                help for config
      --list                List configs
      --set string string   Set a config field to some value
      --unset string        Unset a specific config field

Global flags:
      --api-key string        Your API key to use for the command
      --color string          turn on/off color output (on, off, auto)
      --config string         config file (default is $HOME/.config/stripe/config.toml)
      --device-name string    device name
      --log-level string      log level (debug, info, warn, error) (default "info")
  -p, --project-name string   the project name to read from for config (default "default")

Toms-Work-Mac:diag.net tom$ stripe config --set color off
unknown flag: --set
```

The `--unset color` option worked, as did the `--list` option. Just not the `--set` option.

**Comment by ob-stripe** [comment]
🤦‍♂  Sorry about that. We'll have another fix out shortly.

**Comment by winzig** [comment]
No worries. I did take a look at the code to see if it was obvious, but I'm not familiar with Go.

**Comment by ob-stripe** [comment]
Alright, the `--set` flag should be fixed in v1.2.9.

**Comment by winzig** [comment]
@ob-stripe Confirmed, thanks!
