### ISSUE TITLE
Homebrew error: formulae require at least a URL

### ISSUE THREAD

**Issue by sweetppro** [stripe/stripe-cli#609]
### Issue
Installing via home-brew fails

### Steps to reproduce
`brew install stripe/stripe-cli/stripe`

### Traceback
```
==> Tapping stripe/stripe-cli
Cloning into '/opt/homebrew/Library/Taps/stripe/homebrew-stripe-cli'...
remote: Enumerating objects: 108, done.
remote: Counting objects: 100% (108/108), done.
remote: Compressing objects: 100% (72/72), done.
remote: Total 276 (delta 35), reused 0 (delta 0), pack-reused 168
Receiving objects: 100% (276/276), 35.26 KiB | 802.00 KiB/s, done.
Resolving deltas: 100% (90/90), done.
Error: Invalid formula: /opt/homebrew/Library/Taps/stripe/homebrew-stripe-cli/stripe.rb
formulae require at least a URL
Error: Cannot tap stripe/stripe-cli: invalid syntax in tap!
```

### Environment
macOS 11.2.3 - Apple Silicon (M1)

**Comment by tomelm** [comment]
Sorry about that! This'll be fixed in #608

**Comment by tomer-stripe** [comment]
New version released (1.5.11) with a fixed M1 formula!

**Comment by fabiosalvi** [comment]
I still have this error message in the terminal of VSCode running on WSL2.

**Comment by focusonyoursite** [comment]
#metoo WSL2

**Comment by adimaralimuddin** [comment]
so there is really no way for me to install stripe cli on windows? this is a nightmare.

**Comment by Moongazer** [comment]
Same in Ubuntu 20.04. I had Stripe-CLI working in version 1.5.9 (installed via linuxbrew), but now it forces me to update to the latest version (1.13.8). This update in linuxbrew failes (ALL brew commands related to Stripe-CLI failing with this log, even info):

```
user@dev:/tmp$ brew info stripe
Error: formulae require at least a URL
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:283:in `determine_active_spec'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:214:in `initialize'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:308:in `new'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:308:in `get_formula'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:561:in `factory'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/named_args.rb:98:in `load_formula_or_cask'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/named_args.rb:85:in `block in to_formulae_and_casks_and_unavailable'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/named_args.rb:84:in `map'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/named_args.rb:84:in `to_formulae_and_casks_and_unavailable'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/info.rb:162:in `print_info'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/info.rb:125:in `info'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:98:in `<main>'

```

**Comment by stnikolaus** [comment]
> Same in Ubuntu 20.04. I had Stripe-CLI working in version 1.5.9 (installed via linuxbrew), but now it forces me to update to the latest version (1.13.8). This update in linuxbrew failes (ALL brew commands related to Stripe-CLI failing with this log, even info):
> 
> ```
> user@dev:/tmp$ brew info stripe
> Error: formulae require at least a URL
> Please report this issue:
>   https://docs.brew.sh/Troubleshooting
> /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:283:in `determine_active_spec'
> /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:214:in `initialize'
> /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:308:in `new'
> /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:308:in `get_formula'
> /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formulary.rb:561:in `factory'
> /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/named_args.rb:98:in `load_formula_or_cask'
> /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/named_args.rb:85:in `block in to_formulae_and_casks_and_unavailable'
> /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/named_args.rb:84:in `map'
> /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cli/named_args.rb:84:in `to_formulae_and_casks_and_unavailable'
> /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/info.rb:162:in `print_info'
> /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/info.rb:125:in `info'
> /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:98:in `<main>'
> ```

I have the same problem.

**Comment by Moongazer** [comment]
Workaround: uninstall it from Homebrew and install the binary downloaded from Github (annoying but worked)

**Comment by marty0678** [comment]
Still getting this in WSL2 with brew as well FWIW.

**Comment by arynaq** [comment]
Yep, WSL2

**Comment by Starr2024** [comment]
Payout coming 🔜 Soon Thank You so much for your great work stay updated
